<?php

namespace Database\Seeders;

use App\Models\Origin;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class originSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = array(
            ['slug' => 'AF', 'name' => 'Afghanistan', 'native' => 'غانستان'],
            ['slug' => 'AX', 'name' => 'Åland Islands', 'native' => 'Åland'],
            ['slug' => 'AL', 'name' => 'Albania', 'native' => 'Shqipëri'],
            ['slug' => 'DZ', 'name' => 'Algeria', 'native' => 'الجزائر'],
            ['slug' => 'AS', 'name' => 'American Samoa', 'native' => ''],
            ['slug' => 'AD', 'name' => 'Andorra', 'native' => ''],
            ['slug' => 'AO', 'name' => 'Angola', 'native' => ''],
            ['slug' => 'AI', 'name' => 'Anguilla', 'native' => ''],
            ['slug' => 'AQ', 'name' => 'Antarctica', 'native' => ''],
            ['slug' => 'AG', 'name' => 'Antigua and Barbuda', 'native' => ''],
            ['slug' => 'AR', 'name' => 'Argentina', 'native' => ''],
            ['slug' => 'AM', 'name' => 'Armenia', 'native' => 'Հայաստան'],
            ['slug' => 'AW', 'name' => 'Aruba', 'native' => ''],
            ['slug' => 'AC', 'name' => 'Ascension Island', 'native' => ''],
            ['slug' => 'AU', 'name' => 'Australia', 'native' => ''],
            ['slug' => 'AT', 'name' => 'Austria', 'native' => 'Österreich'],
            ['slug' => 'AZ', 'name' => 'Azerbaijan', 'native' => 'Azərbaycan'],
            ['slug' => 'BS', 'name' => 'Bahamas', 'native' => ''],
            ['slug' => 'BH', 'name' => 'Bahrain', 'native' => 'البحرين'],
            ['slug' => 'BD', 'name' => 'Bangladesh', 'native' => 'বাংলাদেশ'],
            ['slug' => 'BB', 'name' => 'Barbados', 'native' => ''],
            ['slug' => 'BY', 'name' => 'Belarus', 'native' => 'Беларусь'],
            ['slug' => 'BE', 'name' => 'Belgium', 'native' => 'België'],
            ['slug' => 'BZ', 'name' => 'Belize', 'native' => ''],
            ['slug' => 'BJ', 'name' => 'Benin', 'native' => 'Bénin'],
            ['slug' => 'BM', 'name' => 'Bermuda', 'native' => ''],
            ['slug' => 'BT', 'name' => 'Bhutan', 'native' => 'འབྲུག'],
            ['slug' => 'BO', 'name' => 'Bolivia', 'native' => ''],
            ['slug' => 'BA', 'name' => 'Bosnia and Herzegovina', 'native' => 'Босна и Херцеговина'],
            ['slug' => 'BW', 'name' => 'Botswana', 'native' => ''],
            ['slug' => 'BV', 'name' => 'Bouvet Island', 'native' => ''],
            ['slug' => 'BR', 'name' => 'Brazil', 'native' => 'Brasil'],
            ['slug' => 'IO', 'name' => 'British Indian Ocean Territory', 'native' => ''],
            ['slug' => 'VG', 'name' => 'British Virgin Islands', 'native' => ''],
            ['slug' => 'BN', 'name' => 'Brunei', 'native' => ''],
            ['slug' => 'BG', 'name' => 'Bulgaria', 'native' => 'България'],
            ['slug' => 'BF', 'name' => 'Burkina Faso', 'native' => ''],
            ['slug' => 'BI', 'name' => 'Burundi', 'native' => 'Uburundi'],
            ['slug' => 'KH', 'name' => 'Cambodia', 'native' => 'កម្ពុជា'],
            ['slug' => 'CM', 'name' => 'Cameroon', 'native' => 'Cameroun'],
            ['slug' => 'CA', 'name' => 'Canada', 'native' => ''],
            ['slug' => 'IC', 'name' => 'Canary Islands', 'native' => 'islas Canarias'],
            ['slug' => 'CV', 'name' => 'Cape Verde', 'native' => 'Kabu Verdi'],
            ['slug' => 'BQ', 'name' => 'Caribbean Netherlands', 'native' => ''],
            ['slug' => 'KY', 'name' => 'Cayman Islands', 'native' => ''],
            ['slug' => 'CF', 'name' => 'Central African Republic', 'native' => 'République centrafricaine'],
            ['slug' => 'EA', 'name' => 'Ceuta and Melilla', 'native' => 'Ceuta y Melilla'],
            ['slug' => 'TD', 'name' => 'Chad', 'native' => 'Tchad'],
            ['slug' => 'CL', 'name' => 'Chile', 'native' => ''],
            ['slug' => 'CN', 'name' => 'China', 'native' => '中国'],
            ['slug' => 'CX', 'name' => 'Christmas Island', 'native' => ''],
            ['slug' => 'CP', 'name' => 'Clipperton Island', 'native' => ''],
            ['slug' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'native' => 'Kepulauan Cocos (Keeling)'],
            ['slug' => 'CO', 'name' => 'Colombia', 'native' => ''],
            ['slug' => 'KM', 'name' => 'Comoros', 'native' => 'جزر القمر'],
            ['slug' => 'CD', 'name' => 'Congo (DRC)', 'native' => 'Jamhuri ya Kidemokrasia ya Kongo'],
            ['slug' => 'CG', 'name' => 'Congo (Republic)', 'native' => 'Congo-Brazzaville'],
            ['slug' => 'CK', 'name' => 'Cook Islands', 'native' => ''],
            ['slug' => 'CR', 'name' => 'Costa Rica', 'native' => ''],
            ['slug' => 'CI', 'name' => 'Côte d’Ivoire', 'native' => ''],
            ['slug' => 'HR', 'name' => 'Croatia', 'native' => 'Hrvatska'],
            ['slug' => 'CU', 'name' => 'Cuba', 'native' => ''],
            ['slug' => 'CW', 'name' => 'Curaçao', 'native' => ''],
            ['slug' => 'CY', 'name' => 'Cyprus', 'native' => 'Κύπρος'],
            ['slug' => 'CZ', 'name' => 'Czech Republic', 'native' => 'Česká republika'],
            ['slug' => 'DK', 'name' => 'Denmark', 'native' => 'Danmark'],
            ['slug' => 'DG', 'name' => 'Diego Garcia', 'native' => ''],
            ['slug' => 'DJ', 'name' => 'Djibouti', 'native' => ''],
            ['slug' => 'DM', 'name' => 'Dominica', 'native' => ''],
            ['slug' => 'DO', 'name' => 'Dominican Republic', 'native' => 'República Dominicana'],
            ['slug' => 'EC', 'name' => 'Ecuador', 'native' => ''],
            ['slug' => 'EG', 'name' => 'Egypt', 'native' => 'مصر'],
            ['slug' => 'SV', 'name' => 'El Salvador', 'native' => ''],
            ['slug' => 'GQ', 'name' => 'Equatorial Guinea', 'native' => 'Guinea Ecuatorial'],
            ['slug' => 'ER', 'name' => 'Eritrea', 'native' => ''],
            ['slug' => 'EE', 'name' => 'Estonia', 'native' => 'Eesti'],
            ['slug' => 'ET', 'name' => 'Ethiopia', 'native' => ''],
            ['slug' => 'FK', 'name' => 'Falkland Islands', 'native' => 'Islas Malvinas'],
            ['slug' => 'FO', 'name' => 'Faroe Islands', 'native' => 'Føroyar'],
            ['slug' => 'FJ', 'name' => 'Fiji', 'native' => ''],
            ['slug' => 'FI', 'name' => 'Finland', 'native' => 'Suomi'],
            ['slug' => 'FR', 'name' => 'France', 'native' => ''],
            ['slug' => 'GF', 'name' => 'French Guiana', 'native' => 'Guyane française'],
            ['slug' => 'PF', 'name' => 'French Polynesia', 'native' => 'Polynésie française'],
            ['slug' => 'TF', 'name' => 'French Southern Territories', 'native' => 'Terres australes françaises'],
            ['slug' => 'GA', 'name' => 'Gabon', 'native' => ''],
            ['slug' => 'GM', 'name' => 'Gambia', 'native' => ''],
            ['slug' => 'GE', 'name' => 'Georgia', 'native' => 'საქართველო'],
            ['slug' => 'DE', 'name' => 'Germany', 'native' => 'Deutschland'],
            ['slug' => 'GH', 'name' => 'Ghana', 'native' => 'Gaana'],
            ['slug' => 'GI', 'name' => 'Gibraltar', 'native' => ''],
            ['slug' => 'GR', 'name' => 'Greece', 'native' => 'Ελλάδα'],
            ['slug' => 'GL', 'name' => 'Greenland', 'native' => 'Kalaallit Nunaat'],
            ['slug' => 'GD', 'name' => 'Grenada', 'native' => ''],
            ['slug' => 'GP', 'name' => 'Guadeloupe', 'native' => ''],
            ['slug' => 'GU', 'name' => 'Guam', 'native' => ''],
            ['slug' => 'GT', 'name' => 'Guatemala', 'native' => ''],
            ['slug' => 'GG', 'name' => 'Guernsey', 'native' => ''],
            ['slug' => 'GN', 'name' => 'Guinea', 'native' => 'Guinée'],
            ['slug' => 'GW', 'name' => 'Guinea-Bissau', 'native' => 'Guiné Bissau'],
            ['slug' => 'GY', 'name' => 'Guyana', 'native' => ''],
            ['slug' => 'HT', 'name' => 'Haiti', 'native' => ''],
            ['slug' => 'HM', 'name' => 'Heard & McDonald Islands', 'native' => ''],
            ['slug' => 'HN', 'name' => 'Honduras', 'native' => ''],
            ['slug' => 'HK', 'name' => 'Hong Kong', 'native' => '香港'],
            ['slug' => 'HU', 'name' => 'Hungary', 'native' => 'Magyarország'],
            ['slug' => 'IS', 'name' => 'Iceland', 'native' => 'Ísland'],
            ['slug' => 'IN', 'name' => 'India', 'native' => 'भारत'],
            ['slug' => 'ID', 'name' => 'Indonesia', 'native' => ''],
            ['slug' => 'IR', 'name' => 'Iran', 'native' => 'ایران'],
            ['slug' => 'IQ', 'name' => 'Iraq', 'native' => 'العراق'],
            ['slug' => 'IE', 'name' => 'Ireland', 'native' => ''],
            ['slug' => 'IM', 'name' => 'Isle of Man', 'native' => ''],
            ['slug' => 'IL', 'name' => 'Israel', 'native' => 'ישראל'],
            ['slug' => 'IT', 'name' => 'Italy', 'native' => 'Italia'],
            ['slug' => 'JM', 'name' => 'Jamaica', 'native' => ''],
            ['slug' => 'JP', 'name' => 'Japan', 'native' => '日本'],
            ['slug' => 'JE', 'name' => 'Jersey', 'native' => ''],
            ['slug' => 'JO', 'name' => 'Jordan', 'native' => 'الأردن'],
            ['slug' => 'KZ', 'name' => 'Kazakhstan', 'native' => 'Казахстан'],
            ['slug' => 'KE', 'name' => 'Kenya', 'native' => ''],
            ['slug' => 'KI', 'name' => 'Kiribati', 'native' => ''],
            ['slug' => 'XK', 'name' => 'Kosovo', 'native' => 'Kosovë'],
            ['slug' => 'KW', 'name' => 'Kuwait', 'native' => 'الكويت'],
            ['slug' => 'KG', 'name' => 'Kyrgyzstan', 'native' => 'Кыргызстан'],
            ['slug' => 'LA', 'name' => 'Laos', 'native' => 'ລາວ'],
            ['slug' => 'LV', 'name' => 'Latvia', 'native' => 'Latvija'],
            ['slug' => 'LB', 'name' => 'Lebanon', 'native' => 'لبنان'],
            ['slug' => 'LS', 'name' => 'Lesotho', 'native' => ''],
            ['slug' => 'LR', 'name' => 'Liberia', 'native' => ''],
            ['slug' => 'LY', 'name' => 'Libya', 'native' => 'ليبيا'],
            ['slug' => 'LI', 'name' => 'Liechtenstein', 'native' => ''],
            ['slug' => 'LT', 'name' => 'Lithuania', 'native' => 'Lietuva'],
            ['slug' => 'LU', 'name' => 'Luxembourg', 'native' => ''],
            ['slug' => 'MO', 'name' => 'Macau', 'native' => '澳門'],
            ['slug' => 'MK', 'name' => 'Macedonia (FYROM)', 'native' => 'Македонија'],
            ['slug' => 'MG', 'name' => 'Madagascar', 'native' => 'Madagasikara'],
            ['slug' => 'MW', 'name' => 'Malawi', 'native' => ''],
            ['slug' => 'MY', 'name' => 'Malaysia', 'native' => ''],
            ['slug' => 'MV', 'name' => 'Maldives', 'native' => ''],
            ['slug' => 'ML', 'name' => 'Mali', 'native' => ''],
            ['slug' => 'MT', 'name' => 'Malta', 'native' => ''],
            ['slug' => 'MH', 'name' => 'Marshall Islands', 'native' => ''],
            ['slug' => 'MQ', 'name' => 'Martinique', 'native' => ''],
            ['slug' => 'MR', 'name' => 'Mauritania', 'native' => 'موريتانيا'],
            ['slug' => 'MU', 'name' => 'Mauritius', 'native' => 'Moris'],
            ['slug' => 'YT', 'name' => 'Mayotte', 'native' => ''],
            ['slug' => 'MX', 'name' => 'Mexico', 'native' => ''],
            ['slug' => 'FM', 'name' => 'Micronesia', 'native' => ''],
            ['slug' => 'MD', 'name' => 'Moldova', 'native' => 'Republica Moldova'],
            ['slug' => 'MC', 'name' => 'Monaco', 'native' => ''],
            ['slug' => 'MN', 'name' => 'Mongolia', 'native' => 'Монгол'],
            ['slug' => 'ME', 'name' => 'Montenegro', 'native' => 'Crna Gora'],
            ['slug' => 'MS', 'name' => 'Montserrat', 'native' => ''],
            ['slug' => 'MA', 'name' => 'Morocco', 'native' => 'المغرب'],
            ['slug' => 'MZ', 'name' => 'Mozambique', 'native' => 'Moçambique'],
            ['slug' => 'MM', 'name' => 'Myanmar (Burma)', 'native' => 'မြန်မာ'],
            ['slug' => 'NA', 'name' => 'Namibia', 'native' => 'Namibië'],
            ['slug' => 'NR', 'name' => 'Nauru', 'native' => ''],
            ['slug' => 'NP', 'name' => 'Nepal', 'native' => 'नेपाल'],
            ['slug' => 'NL', 'name' => 'Netherlands', 'native' => 'Nederland'],
            ['slug' => 'NC', 'name' => 'New Caledonia', 'native' => 'Nouvelle-Calédonie'],
            ['slug' => 'NZ', 'name' => 'New Zealand', 'native' => ''],
            ['slug' => 'NI', 'name' => 'Nicaragua', 'native' => ''],
            ['slug' => 'NE', 'name' => 'Niger', 'native' => 'Nijar'],
            ['slug' => 'NG', 'name' => 'Nigeria', 'native' => ''],
            ['slug' => 'NU', 'name' => 'Niue', 'native' => ''],
            ['slug' => 'NF', 'name' => 'Norfolk Island', 'native' => ''],
            ['slug' => 'MP', 'name' => 'Northern Mariana Islands', 'native' => ''],
            ['slug' => 'KP', 'name' => 'North Korea', 'native' => '조선 민주주의 인민 공화국'],
            ['slug' => 'NO', 'name' => 'Norway', 'native' => 'Norge'],
            ['slug' => 'OM', 'name' => 'Oman', 'native' => 'عُمان'],
            ['slug' => 'PK', 'name' => 'Pakistan', 'native' => 'پاکستان'],
            ['slug' => 'PW', 'name' => 'Palau', 'native' => ''],
            ['slug' => 'PS', 'name' => 'Palestine', 'native' => 'فلسطين'],
            ['slug' => 'PA', 'name' => 'Panama', 'native' => ''],
            ['slug' => 'PG', 'name' => 'Papua New Guinea', 'native' => ''],
            ['slug' => 'PY', 'name' => 'Paraguay', 'native' => ''],
            ['slug' => 'PE', 'name' => 'Peru', 'native' => 'Perú'],
            ['slug' => 'PH', 'name' => 'Philippines', 'native' => ''],
            ['slug' => 'PN', 'name' => 'Pitcairn Islands', 'native' => ''],
            ['slug' => 'PL', 'name' => 'Poland', 'native' => 'Polska'],
            ['slug' => 'PT', 'name' => 'Portugal', 'native' => ''],
            ['slug' => 'PR', 'name' => 'Puerto Rico', 'native' => ''],
            ['slug' => 'QA', 'name' => 'Qatar', 'native' => 'قطر'],
            ['slug' => 'RE', 'name' => 'Réunion', 'native' => 'La Réunion'],
            ['slug' => 'RO', 'name' => 'Romania', 'native' => 'România'],
            ['slug' => 'RU', 'name' => 'Russia', 'native' => 'Россия'],
            ['slug' => 'RW', 'name' => 'Rwanda', 'native' => ''],
            ['slug' => 'BL', 'name' => 'Saint Barthélemy', 'native' => 'Saint-Barthélemy'],
            ['slug' => 'SH', 'name' => 'Saint Helena', 'native' => ''],
            ['slug' => 'KN', 'name' => 'Saint Kitts and Nevis', 'native' => ''],
            ['slug' => 'LC', 'name' => 'Saint Lucia', 'native' => ''],
            ['slug' => 'MF', 'name' => 'Saint Martin', 'native' => ''],
            ['slug' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'native' => 'Saint-Pierre-et-Miquelon'],
            ['slug' => 'WS', 'name' => 'Samoa', 'native' => ''],
            ['slug' => 'SM', 'name' => 'San Marino', 'native' => ''],
            ['slug' => 'ST', 'name' => 'São Tomé and Príncipe', 'native' => 'São Tomé e Príncipe'],
            ['slug' => 'SA', 'name' => 'Saudi Arabia', 'native' => 'المملكة العربية السعودية'],
            ['slug' => 'SN', 'name' => 'Senegal', 'native' => 'Sénégal'],
            ['slug' => 'RS', 'name' => 'Serbia', 'native' => 'Србија'],
            ['slug' => 'SC', 'name' => 'Seychelles', 'native' => ''],
            ['slug' => 'SL', 'name' => 'Sierra Leone', 'native' => ''],
            ['slug' => 'SG', 'name' => 'Singapore', 'native' => ''],
            ['slug' => 'SX', 'name' => 'Sint Maarten', 'native' => ''],
            ['slug' => 'SK', 'name' => 'Slovakia', 'native' => 'Slovensko'],
            ['slug' => 'SI', 'name' => 'Slovenia', 'native' => 'Slovenija'],
            ['slug' => 'SB', 'name' => 'Solomon Islands', 'native' => ''],
            ['slug' => 'SO', 'name' => 'Somalia', 'native' => 'Soomaaliya'],
            ['slug' => 'ZA', 'name' => 'South Africa', 'native' => ''],
            ['slug' => 'GS', 'name' => 'South Georgia & South Sandwich Islands', 'native' => ''],
            ['slug' => 'KR', 'name' => 'South Korea', 'native' => '대한민국'],
            ['slug' => 'SS', 'name' => 'South Sudan', 'native' => 'جنوب السودان'],
            ['slug' => 'ES', 'name' => 'Spain', 'native' => 'España'],
            ['slug' => 'LK', 'name' => 'Sri Lanka', 'native' => 'ශ්‍රී ලංකාව'],
            ['slug' => 'VC', 'name' => 'St. Vincent & Grenadines', 'native' => ''],
            ['slug' => 'SD', 'name' => 'Sudan', 'native' => 'السودان'],
            ['slug' => 'SR', 'name' => 'Suriname', 'native' => ''],
            ['slug' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'native' => 'Svalbard og Jan Mayen'],
            ['slug' => 'SZ', 'name' => 'Swaziland', 'native' => ''],
            ['slug' => 'SE', 'name' => 'Sweden', 'native' => 'Sverige'],
            ['slug' => 'CH', 'name' => 'Switzerland', 'native' => 'Schweiz'],
            ['slug' => 'SY', 'name' => 'Syria', 'native' => 'سوريا'],
            ['slug' => 'TW', 'name' => 'Taiwan', 'native' => '台灣'],
            ['slug' => 'TJ', 'name' => 'Tajikistan', 'native' => ''],
            ['slug' => 'TZ', 'name' => 'Tanzania', 'native' => ''],
            ['slug' => 'TH', 'name' => 'Thailand', 'native' => 'ไทย'],
            ['slug' => 'TL', 'name' => 'Timor-Leste', 'native' => ''],
            ['slug' => 'TG', 'name' => 'Togo', 'native' => ''],
            ['slug' => 'TK', 'name' => 'Tokelau', 'native' => ''],
            ['slug' => 'TO', 'name' => 'Tonga', 'native' => ''],
            ['slug' => 'TT', 'name' => 'Trinidad and Tobago', 'native' => ''],
            ['slug' => 'TA', 'name' => 'Tristan da Cunha', 'native' => ''],
            ['slug' => 'TN', 'name' => 'Tunisia', 'native' => 'تونس'],
            ['slug' => 'TR', 'name' => 'Turkey', 'native' => 'Türkiye'],
            ['slug' => 'TM', 'name' => 'Turkmenistan', 'native' => ''],
            ['slug' => 'TC', 'name' => 'Turks and Caicos Islands', 'native' => ''],
            ['slug' => 'TV', 'name' => 'Tuvalu', 'native' => ''],
            ['slug' => 'UM', 'name' => 'U.S. Outlying Islands', 'native' => ''],
            ['slug' => 'VI', 'name' => 'U.S. Virgin Islands', 'native' => ''],
            ['slug' => 'UG', 'name' => 'Uganda', 'native' => ''],
            ['slug' => 'UA', 'name' => 'Ukraine', 'native' => 'Україна'],
            ['slug' => 'AE', 'name' => 'United Arab Emirates', 'native' => 'الإمارات العربية المتحدة'],
            ['slug' => 'GB', 'name' => 'United Kingdom', 'native' => ''],
            ['slug' => 'US', 'name' => 'United States', 'native' => ''],
            ['slug' => 'UY', 'name' => 'Uruguay', 'native' => ''],
            ['slug' => 'UZ', 'name' => 'Uzbekistan', 'native' => 'Oʻzbekiston'],
            ['slug' => 'VU', 'name' => 'Vanuatu', 'native' => ''],
            ['slug' => 'VA', 'name' => 'Vatican City', 'native' => 'Città del Vaticano'],
            ['slug' => 'VE', 'name' => 'Venezuela', 'native' => ''],
            ['slug' => 'VN', 'name' => 'Vietnam', 'native' => 'Việt Nam'],
            ['slug' => 'WF', 'name' => 'Wallis and Futuna', 'native' => ''],
            ['slug' => 'EH', 'name' => 'Western Sahara', 'native' => 'الصحراء الغربية'],
            ['slug' => 'YE', 'name' => 'Yemen', 'native' => 'اليمن'],
            ['slug' => 'ZM', 'name' => 'Zambia', 'native' => ''],
            ['slug' => 'ZW', 'name' => 'Zimbabwe', 'native' => '']
        );
        Origin::insert($data);
    }
}
