<?php

namespace Database\Seeders;

use App\Models\Origin;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class originSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = array(
            ['slug' => 'AF', 'name' => 'Afghanistan', 'name_al' => '', 'name_de' => '', 'native' => 'غانستان', 'active' => false],
            ['slug' => 'AX', 'name' => 'Åland Islands', 'name_al' => '', 'name_de' => '', 'native' => 'Åland', 'active' => false],
            ['slug' => 'AL', 'name' => 'Albania', 'name_al' => 'Shqip', 'name_de' => 'Albanisch', 'native' => 'Shqip', 'active' => true],
            ['slug' => 'DZ', 'name' => 'Algeria', 'name_al' => '', 'name_de' => '', 'native' => 'الجزائر', 'active' => false],
            ['slug' => 'AS', 'name' => 'American Samoa', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'AD', 'name' => 'Andorra', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'AO', 'name' => 'Angola', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'AI', 'name' => 'Anguilla', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'AQ', 'name' => 'Antarctica', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'AG', 'name' => 'Antigua and Barbuda', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'AR', 'name' => 'Argentina', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'AM', 'name' => 'Armenia', 'name_al' => '', 'name_de' => '', 'native' => 'Հայաստան', 'active' => false],
            ['slug' => 'AW', 'name' => 'Aruba', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'AC', 'name' => 'Ascension Island', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'AU', 'name' => 'Australia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'AT', 'name' => 'Austria', 'name_al' => '', 'name_de' => '', 'native' => 'Österreich', 'active' => false],
            ['slug' => 'AZ', 'name' => 'Azerbaijan', 'name_al' => '', 'name_de' => '', 'native' => 'Azərbaycan', 'active' => false],
            ['slug' => 'BS', 'name' => 'Bahamas', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BH', 'name' => 'Bahrain', 'name_al' => '', 'name_de' => '', 'native' => 'البحرين', 'active' => false],
            ['slug' => 'BD', 'name' => 'Bangladesh', 'name_al' => '', 'name_de' => '', 'native' => 'বাংলাদেশ', 'active' => false],
            ['slug' => 'BB', 'name' => 'Barbados', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BY', 'name' => 'Belarus', 'name_al' => '', 'name_de' => '', 'native' => 'Беларусь', 'active' => false],
            ['slug' => 'BE', 'name' => 'Belgium', 'name_al' => '', 'name_de' => '', 'native' => 'België', 'active' => false],
            ['slug' => 'BZ', 'name' => 'Belize', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BJ', 'name' => 'Benin', 'name_al' => '', 'name_de' => '', 'native' => 'Bénin', 'active' => false],
            ['slug' => 'BM', 'name' => 'Bermuda', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BT', 'name' => 'Bhutan', 'name_al' => '', 'name_de' => '', 'native' => 'འབྲུག', 'active' => false],
            ['slug' => 'BO', 'name' => 'Bolivia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BA', 'name' => 'Bosnia and Herzegovina', 'name_al' => '', 'name_de' => '', 'native' => 'Босна и Херцеговина', 'active' => false],
            ['slug' => 'BW', 'name' => 'Botswana', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BV', 'name' => 'Bouvet Island', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BR', 'name' => 'Brazil', 'name_al' => '', 'name_de' => '', 'native' => 'Brasil', 'active' => false],
            ['slug' => 'IO', 'name' => 'British Indian Ocean Territory', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'VG', 'name' => 'British Virgin Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BN', 'name' => 'Brunei', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BG', 'name' => 'Bulgaria', 'name_al' => '', 'name_de' => '', 'native' => 'България', 'active' => false],
            ['slug' => 'BF', 'name' => 'Burkina Faso', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BI', 'name' => 'Burundi', 'name_al' => '', 'name_de' => '', 'native' => 'Uburundi', 'active' => false],
            ['slug' => 'KH', 'name' => 'Cambodia', 'name_al' => '', 'name_de' => '', 'native' => 'កម្ពុជា', 'active' => false],
            ['slug' => 'CM', 'name' => 'Cameroon', 'name_al' => '', 'name_de' => '', 'native' => 'Cameroun', 'active' => false],
            ['slug' => 'CA', 'name' => 'Canada', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'IC', 'name' => 'Canary Islands', 'name_al' => '', 'name_de' => '', 'native' => 'islas Canarias', 'active' => false],
            ['slug' => 'CV', 'name' => 'Cape Verde', 'name_al' => '', 'name_de' => '', 'native' => 'Kabu Verdi', 'active' => false],
            ['slug' => 'BQ', 'name' => 'Caribbean Netherlands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'KY', 'name' => 'Cayman Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'CF', 'name' => 'Central African Republic', 'name_al' => '', 'name_de' => '', 'native' => 'République centrafricaine', 'active' => false],
            ['slug' => 'EA', 'name' => 'Ceuta and Melilla', 'name_al' => '', 'name_de' => '', 'native' => 'Ceuta y Melilla', 'active' => false],
            ['slug' => 'TD', 'name' => 'Chad', 'name_al' => '', 'name_de' => '', 'native' => 'Tchad', 'active' => false],
            ['slug' => 'CL', 'name' => 'Chile', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'CN', 'name' => 'China', 'name_al' => '', 'name_de' => '', 'native' => '中国', 'active' => false],
            ['slug' => 'CX', 'name' => 'Christmas Island', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'CP', 'name' => 'Clipperton Island', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'name_al' => '', 'name_de' => '', 'native' => 'Kepulauan Cocos (Keeling)', 'active' => false],
            ['slug' => 'CO', 'name' => 'Colombia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'KM', 'name' => 'Comoros', 'name_al' => '', 'name_de' => '', 'native' => 'جزر القمر', 'active' => false],
            ['slug' => 'CD', 'name' => 'Congo (DRC)', 'name_al' => '', 'name_de' => '', 'native' => 'Jamhuri ya Kidemokrasia ya Kongo', 'active' => false],
            ['slug' => 'CG', 'name' => 'Congo (Republic)', 'name_al' => '', 'name_de' => '', 'native' => 'Congo-Brazzaville', 'active' => false],
            ['slug' => 'CK', 'name' => 'Cook Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'CR', 'name' => 'Costa Rica', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'CI', 'name' => 'Côte d’Ivoire', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'HR', 'name' => 'Croatia', 'name_al' => '', 'name_de' => '', 'native' => 'Hrvatska', 'active' => false],
            ['slug' => 'CU', 'name' => 'Cuba', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'CW', 'name' => 'Curaçao', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'CY', 'name' => 'Cyprus', 'name_al' => '', 'name_de' => '', 'native' => 'Κύπρος', 'active' => false],
            ['slug' => 'CZ', 'name' => 'Czech Republic', 'name_al' => '', 'name_de' => '', 'native' => 'Česká republika', 'active' => false],
            ['slug' => 'DK', 'name' => 'Denmark', 'name_al' => '', 'name_de' => '', 'native' => 'Danmark', 'active' => false],
            ['slug' => 'DG', 'name' => 'Diego Garcia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'DJ', 'name' => 'Djibouti', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'DM', 'name' => 'Dominica', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'DO', 'name' => 'Dominican Republic', 'name_al' => '', 'name_de' => '', 'native' => 'República Dominicana', 'active' => false],
            ['slug' => 'EC', 'name' => 'Ecuador', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'EG', 'name' => 'Egypt', 'name_al' => '', 'name_de' => '', 'native' => 'مصر', 'active' => false],
            ['slug' => 'SV', 'name' => 'El Salvador', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GQ', 'name' => 'Equatorial Guinea', 'name_al' => '', 'name_de' => '', 'native' => 'Guinea Ecuatorial', 'active' => false],
            ['slug' => 'ER', 'name' => 'Eritrea', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'EE', 'name' => 'Estonia', 'name_al' => '', 'name_de' => '', 'native' => 'Eesti', 'active' => false],
            ['slug' => 'ET', 'name' => 'Ethiopia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'FK', 'name' => 'Falkland Islands', 'name_al' => '', 'name_de' => '', 'native' => 'Islas Malvinas', 'active' => false],
            ['slug' => 'FO', 'name' => 'Faroe Islands', 'name_al' => '', 'name_de' => '', 'native' => 'Føroyar', 'active' => false],
            ['slug' => 'FJ', 'name' => 'Fiji', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'FI', 'name' => 'Finland', 'name_al' => '', 'name_de' => '', 'native' => 'Suomi', 'active' => false],
            ['slug' => 'FR', 'name' => 'France', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GF', 'name' => 'French Guiana', 'name_al' => '', 'name_de' => '', 'native' => 'Guyane française', 'active' => false],
            ['slug' => 'PF', 'name' => 'French Polynesia', 'name_al' => '', 'name_de' => '', 'native' => 'Polynésie française', 'active' => false],
            ['slug' => 'TF', 'name' => 'French Southern Territories', 'name_al' => '', 'name_de' => '', 'native' => 'Terres australes françaises', 'active' => false],
            ['slug' => 'GA', 'name' => 'Gabon', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GM', 'name' => 'Gambia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GE', 'name' => 'Georgia', 'name_al' => '', 'name_de' => '', 'native' => 'საქართველო', 'active' => false],
            ['slug' => 'DE', 'name' => 'Germany', 'name_al' => '', 'name_de' => '', 'native' => 'Deutschland', 'active' => false],
            ['slug' => 'GH', 'name' => 'Ghana', 'name_al' => '', 'name_de' => '', 'native' => 'Gaana', 'active' => false],
            ['slug' => 'GI', 'name' => 'Gibraltar', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GR', 'name' => 'Greece', 'name_al' => '', 'name_de' => '', 'native' => 'Ελλάδα', 'active' => false],
            ['slug' => 'GL', 'name' => 'Greenland', 'name_al' => '', 'name_de' => '', 'native' => 'Kalaallit Nunaat', 'active' => false],
            ['slug' => 'GD', 'name' => 'Grenada', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GP', 'name' => 'Guadeloupe', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GU', 'name' => 'Guam', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GT', 'name' => 'Guatemala', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GG', 'name' => 'Guernsey', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GN', 'name' => 'Guinea', 'name_al' => '', 'name_de' => '', 'native' => 'Guinée', 'active' => false],
            ['slug' => 'GW', 'name' => 'Guinea-Bissau', 'name_al' => '', 'name_de' => '', 'native' => 'Guiné Bissau', 'active' => false],
            ['slug' => 'GY', 'name' => 'Guyana', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'HT', 'name' => 'Haiti', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'HM', 'name' => 'Heard & McDonald Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'HN', 'name' => 'Honduras', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'HK', 'name' => 'Hong Kong', 'name_al' => '', 'name_de' => '', 'native' => '香港', 'active' => false],
            ['slug' => 'HU', 'name' => 'Hungary', 'name_al' => '', 'name_de' => '', 'native' => 'Magyarország', 'active' => false],
            ['slug' => 'IS', 'name' => 'Iceland', 'name_al' => '', 'name_de' => '', 'native' => 'Ísland', 'active' => false],
            ['slug' => 'IN', 'name' => 'India', 'name_al' => '', 'name_de' => '', 'native' => 'भारत', 'active' => false],
            ['slug' => 'ID', 'name' => 'Indonesia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'IR', 'name' => 'Iran', 'name_al' => '', 'name_de' => '', 'native' => 'ایران', 'active' => false],
            ['slug' => 'IQ', 'name' => 'Iraq', 'name_al' => '', 'name_de' => '', 'native' => 'العراق', 'active' => false],
            ['slug' => 'IE', 'name' => 'Ireland', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'IS', 'name' => 'Islam', 'name_al' => '', 'name_de' => '', 'native' => 'Islam', 'active' => true],
            ['slug' => 'IM', 'name' => 'Isle of Man', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'IL', 'name' => 'Israel', 'name_al' => '', 'name_de' => '', 'native' => 'ישראל', 'active' => false],
            ['slug' => 'IT', 'name' => 'Italy', 'name_al' => '', 'name_de' => '', 'native' => 'Italia', 'active' => false],
            ['slug' => 'JM', 'name' => 'Jamaica', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'JP', 'name' => 'Japan', 'name_al' => '', 'name_de' => '', 'native' => '日本', 'active' => false],
            ['slug' => 'JE', 'name' => 'Jersey', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'JO', 'name' => 'Jordan', 'name_al' => '', 'name_de' => '', 'native' => 'الأردن', 'active' => false],
            ['slug' => 'KZ', 'name' => 'Kazakhstan', 'name_al' => '', 'name_de' => '', 'native' => 'Казахстан', 'active' => false],
            ['slug' => 'KE', 'name' => 'Kenya', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'KI', 'name' => 'Kiribati', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'KW', 'name' => 'Kuwait', 'name_al' => '', 'name_de' => '', 'native' => 'الكويت', 'active' => false],
            ['slug' => 'KG', 'name' => 'Kyrgyzstan', 'name_al' => '', 'name_de' => '', 'native' => 'Кыргызстан', 'active' => false],
            ['slug' => 'LA', 'name' => 'Laos', 'name_al' => '', 'name_de' => '', 'native' => 'ລາວ', 'active' => false],
            ['slug' => 'LV', 'name' => 'Latvia', 'name_al' => '', 'name_de' => '', 'native' => 'Latvija', 'active' => false],
            ['slug' => 'LB', 'name' => 'Lebanon', 'name_al' => '', 'name_de' => '', 'native' => 'لبنان', 'active' => false],
            ['slug' => 'LS', 'name' => 'Lesotho', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'LR', 'name' => 'Liberia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'LY', 'name' => 'Libya', 'name_al' => '', 'name_de' => '', 'native' => 'ليبيا', 'active' => false],
            ['slug' => 'LI', 'name' => 'Liechtenstein', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'LT', 'name' => 'Lithuania', 'name_al' => '', 'name_de' => '', 'native' => 'Lietuva', 'active' => false],
            ['slug' => 'LU', 'name' => 'Luxembourg', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MO', 'name' => 'Macau', 'name_al' => '', 'name_de' => '', 'native' => '澳門', 'active' => false],
            ['slug' => 'MK', 'name' => 'Macedonia (FYROM)', 'name_al' => '', 'name_de' => '', 'native' => 'Македонија', 'active' => false],
            ['slug' => 'MG', 'name' => 'Madagascar', 'name_al' => '', 'name_de' => '', 'native' => 'Madagasikara', 'active' => false],
            ['slug' => 'MW', 'name' => 'Malawi', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MY', 'name' => 'Malaysia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MV', 'name' => 'Maldives', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'ML', 'name' => 'Mali', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MT', 'name' => 'Malta', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MH', 'name' => 'Marshall Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MQ', 'name' => 'Martinique', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MR', 'name' => 'Mauritania', 'name_al' => '', 'name_de' => '', 'native' => 'موريتانيا', 'active' => false],
            ['slug' => 'MU', 'name' => 'Mauritius', 'name_al' => '', 'name_de' => '', 'native' => 'Moris', 'active' => false],
            ['slug' => 'YT', 'name' => 'Mayotte', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MX', 'name' => 'Mexico', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'FM', 'name' => 'Micronesia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MD', 'name' => 'Moldova', 'name_al' => '', 'name_de' => '', 'native' => 'Republica Moldova', 'active' => false],
            ['slug' => 'MC', 'name' => 'Monaco', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MN', 'name' => 'Mongolia', 'name_al' => '', 'name_de' => '', 'native' => 'Монгол', 'active' => false],
            ['slug' => 'ME', 'name' => 'Montenegro', 'name_al' => '', 'name_de' => '', 'native' => 'Crna Gora', 'active' => false],
            ['slug' => 'MS', 'name' => 'Montserrat', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MA', 'name' => 'Morocco', 'name_al' => '', 'name_de' => '', 'native' => 'المغرب', 'active' => false],
            ['slug' => 'MZ', 'name' => 'Mozambique', 'name_al' => '', 'name_de' => '', 'native' => 'Moçambique', 'active' => false],
            ['slug' => 'MM', 'name' => 'Myanmar (Burma)', 'name_al' => '', 'name_de' => '', 'native' => 'မြန်မာ', 'active' => false],
            ['slug' => 'NA', 'name' => 'Namibia', 'name_al' => '', 'name_de' => '', 'native' => 'Namibië', 'active' => false],
            ['slug' => 'NR', 'name' => 'Nauru', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'NP', 'name' => 'Nepal', 'name_al' => '', 'name_de' => '', 'native' => 'नेपाल', 'active' => false],
            ['slug' => 'NL', 'name' => 'Netherlands', 'name_al' => '', 'name_de' => '', 'native' => 'Nederland', 'active' => false],
            ['slug' => 'NC', 'name' => 'New Caledonia', 'name_al' => '', 'name_de' => '', 'native' => 'Nouvelle-Calédonie', 'active' => false],
            ['slug' => 'NZ', 'name' => 'New Zealand', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'NI', 'name' => 'Nicaragua', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'NE', 'name' => 'Niger', 'name_al' => '', 'name_de' => '', 'native' => 'Nijar', 'active' => false],
            ['slug' => 'NG', 'name' => 'Nigeria', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'NU', 'name' => 'Niue', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'NF', 'name' => 'Norfolk Island', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MP', 'name' => 'Northern Mariana Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'KP', 'name' => 'North Korea', 'name_al' => '', 'name_de' => '', 'native' => '조선 민주주의 인민 공화국', 'active' => false],
            ['slug' => 'NO', 'name' => 'Norway', 'name_al' => '', 'name_de' => '', 'native' => 'Norge', 'active' => false],
            ['slug' => 'OM', 'name' => 'Oman', 'name_al' => '', 'name_de' => '', 'native' => 'عُمان', 'active' => false],
            ['slug' => 'PK', 'name' => 'Pakistan', 'name_al' => '', 'name_de' => '', 'native' => 'پاکستان', 'active' => false],
            ['slug' => 'PW', 'name' => 'Palau', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'PS', 'name' => 'Palestine', 'name_al' => '', 'name_de' => '', 'native' => 'فلسطين', 'active' => false],
            ['slug' => 'PA', 'name' => 'Panama', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'PG', 'name' => 'Papua New Guinea', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'PY', 'name' => 'Paraguay', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'PE', 'name' => 'Peru', 'name_al' => '', 'name_de' => '', 'native' => 'Perú', 'active' => false],
            ['slug' => 'PH', 'name' => 'Philippines', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'PN', 'name' => 'Pitcairn Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'PL', 'name' => 'Poland', 'name_al' => '', 'name_de' => '', 'native' => 'Polska', 'active' => false],
            ['slug' => 'PT', 'name' => 'Portugal', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'PR', 'name' => 'Puerto Rico', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'QA', 'name' => 'Qatar', 'name_al' => '', 'name_de' => '', 'native' => 'قطر', 'active' => false],
            ['slug' => 'RE', 'name' => 'Réunion', 'name_al' => '', 'name_de' => '', 'native' => 'La Réunion', 'active' => false],
            ['slug' => 'RO', 'name' => 'Romania', 'name_al' => '', 'name_de' => '', 'native' => 'România', 'active' => false],
            ['slug' => 'RU', 'name' => 'Russia', 'name_al' => '', 'name_de' => '', 'native' => 'Россия', 'active' => false],
            ['slug' => 'RW', 'name' => 'Rwanda', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'BL', 'name' => 'Saint Barthélemy', 'name_al' => '', 'name_de' => '', 'native' => 'Saint-Barthélemy', 'active' => false],
            ['slug' => 'SH', 'name' => 'Saint Helena', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'KN', 'name' => 'Saint Kitts and Nevis', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'LC', 'name' => 'Saint Lucia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'MF', 'name' => 'Saint Martin', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'name_al' => '', 'name_de' => '', 'native' => 'Saint-Pierre-et-Miquelon', 'active' => false],
            ['slug' => 'WS', 'name' => 'Samoa', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'SM', 'name' => 'San Marino', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'ST', 'name' => 'São Tomé and Príncipe', 'name_al' => '', 'name_de' => '', 'native' => 'São Tomé e Príncipe', 'active' => false],
            ['slug' => 'SA', 'name' => 'Saudi Arabia', 'name_al' => '', 'name_de' => '', 'native' => 'المملكة العربية السعودية', 'active' => false],
            ['slug' => 'SN', 'name' => 'Senegal', 'name_al' => '', 'name_de' => '', 'native' => 'Sénégal', 'active' => false],
            ['slug' => 'RS', 'name' => 'Serbia', 'name_al' => '', 'name_de' => '', 'native' => 'Србија', 'active' => false],
            ['slug' => 'SC', 'name' => 'Seychelles', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'SL', 'name' => 'Sierra Leone', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'SG', 'name' => 'Singapore', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'SX', 'name' => 'Sint Maarten', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'SK', 'name' => 'Slovakia', 'name_al' => '', 'name_de' => '', 'native' => 'Slovensko', 'active' => false],
            ['slug' => 'SI', 'name' => 'Slovenia', 'name_al' => '', 'name_de' => '', 'native' => 'Slovenija', 'active' => false],
            ['slug' => 'SB', 'name' => 'Solomon Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'SO', 'name' => 'Somalia', 'name_al' => '', 'name_de' => '', 'native' => 'Soomaaliya', 'active' => false],
            ['slug' => 'ZA', 'name' => 'South Africa', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'GS', 'name' => 'South Georgia & South Sandwich Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'KR', 'name' => 'South Korea', 'name_al' => '', 'name_de' => '', 'native' => '대한민국', 'active' => false],
            ['slug' => 'SS', 'name' => 'South Sudan', 'name_al' => '', 'name_de' => '', 'native' => 'جنوب السودان', 'active' => false],
            ['slug' => 'ES', 'name' => 'Spain', 'name_al' => '', 'name_de' => '', 'native' => 'España', 'active' => false],
            ['slug' => 'LK', 'name' => 'Sri Lanka', 'name_al' => '', 'name_de' => '', 'native' => 'ශ්‍රී ලංකාව', 'active' => false],
            ['slug' => 'VC', 'name' => 'St. Vincent & Grenadines', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'SD', 'name' => 'Sudan', 'name_al' => '', 'name_de' => '', 'native' => 'السودان', 'active' => false],
            ['slug' => 'SR', 'name' => 'Suriname', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'name_al' => '', 'name_de' => '', 'native' => 'Svalbard og Jan Mayen', 'active' => false],
            ['slug' => 'SZ', 'name' => 'Swaziland', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'SE', 'name' => 'Sweden', 'name_al' => '', 'name_de' => '', 'native' => 'Sverige', 'active' => false],
            ['slug' => 'CH', 'name' => 'Switzerland', 'name_al' => '', 'name_de' => '', 'native' => 'Schweiz', 'active' => false],
            ['slug' => 'SY', 'name' => 'Syria', 'name_al' => '', 'name_de' => '', 'native' => 'سوريا', 'active' => false],
            ['slug' => 'TW', 'name' => 'Taiwan', 'name_al' => '', 'name_de' => '', 'native' => '台灣', 'active' => false],
            ['slug' => 'TJ', 'name' => 'Tajikistan', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'TZ', 'name' => 'Tanzania', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'TH', 'name' => 'Thailand', 'name_al' => '', 'name_de' => '', 'native' => 'ไทย', 'active' => false],
            ['slug' => 'TL', 'name' => 'Timor-Leste', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'TG', 'name' => 'Togo', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'TK', 'name' => 'Tokelau', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'TO', 'name' => 'Tonga', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'TT', 'name' => 'Trinidad and Tobago', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'TA', 'name' => 'Tristan da Cunha', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'TN', 'name' => 'Tunisia', 'name_al' => '', 'name_de' => '', 'native' => 'تونس', 'active' => false],
            ['slug' => 'TR', 'name' => 'Turkey', 'name_al' => '', 'name_de' => '', 'native' => 'Türkiye', 'active' => false],
            ['slug' => 'TM', 'name' => 'Turkmenistan', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'TC', 'name' => 'Turks and Caicos Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'TV', 'name' => 'Tuvalu', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'UM', 'name' => 'U.S. Outlying Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'VI', 'name' => 'U.S. Virgin Islands', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'UG', 'name' => 'Uganda', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'UA', 'name' => 'Ukraine', 'name_al' => '', 'name_de' => '', 'native' => 'Україна', 'active' => false],
            ['slug' => 'AE', 'name' => 'United Arab Emirates', 'name_al' => '', 'name_de' => '', 'native' => 'الإمارات العربية المتحدة', 'active' => false],
            ['slug' => 'GB', 'name' => 'United Kingdom', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'US', 'name' => 'United States', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'UY', 'name' => 'Uruguay', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'UZ', 'name' => 'Uzbekistan', 'name_al' => '', 'name_de' => '', 'native' => 'Oʻzbekiston', 'active' => false],
            ['slug' => 'VU', 'name' => 'Vanuatu', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'VA', 'name' => 'Vatican City', 'name_al' => '', 'name_de' => '', 'native' => 'Città del Vaticano', 'active' => false],
            ['slug' => 'VE', 'name' => 'Venezuela', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'VN', 'name' => 'Vietnam', 'name_al' => '', 'name_de' => '', 'native' => 'Việt Nam', 'active' => false],
            ['slug' => 'WF', 'name' => 'Wallis and Futuna', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'EH', 'name' => 'Western Sahara', 'name_al' => '', 'name_de' => '', 'native' => 'الصحراء الغربية', 'active' => false],
            ['slug' => 'YE', 'name' => 'Yemen', 'name_al' => '', 'name_de' => '', 'native' => 'اليمن', 'active' => false],
            ['slug' => 'ZM', 'name' => 'Zambia', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false],
            ['slug' => 'ZW', 'name' => 'Zimbabwe', 'name_al' => '', 'name_de' => '', 'native' => '', 'active' => false]
        );
        Origin::insert($data);
    }
}
