<?php

namespace Database\Seeders;

use App\Models\Origin;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class OriginSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            ['name' =>"Aboriginal", 'name_de' => "Aborigine", 'name_al' => "Aborigjinale", 'active' => true],
            ['name' =>"Africa", 'name_de' => "Afrika", 'name_al' => "Afrika", 'active' => true],
            ['name' =>"Ghana", 'name_de' => "Ghana", 'name_al' => "Gana", 'active' => true],
            ['name' =>"West Africa", 'name_de' => "Westafrika", 'name_al' => "Afrika Perendimore", 'active' => true],
            ['name' =>"Uganda", 'name_de' => "Uganda", 'name_al' => "Uganda", 'active' => true],
            ['name' =>"Ethiopia", 'name_de' => "Äthiopien", 'name_al' => "Etiopia", 'active' => true],
            ['name' =>"Botswana", 'name_de' => "Botswana", 'name_al' => "Botsvana", 'active' => true],
            ['name' =>"Nigeria", 'name_de' => "Nigeria", 'name_al' => "Nigeria", 'active' => true],
            ['name' =>"Cameroon", 'name_de' => "Kamerun", 'name_al' => "Kamerun", 'active' => true],
            ['name' =>"East Africa", 'name_de' => "Ostafrika", 'name_al' => "Afrika Lindore", 'active' => true],
            ['name' =>"Kenya", 'name_de' => "Kenia", 'name_al' => "Kenia", 'active' => true],
            ['name' =>"Malawi", 'name_de' => "Malawi", 'name_al' => "Malavi", 'active' => true],
            ['name' =>"North Africa", 'name_de' => "Nordafrika", 'name_al' => "Afrika Veriore", 'active' => true],
            ['name' =>"Tanzania", 'name_de' => "Tansania", 'name_al' => "Tanzania", 'active' => true],
            ['name' =>"South Africa", 'name_de' => "Südafrika", 'name_al' => "Afrika e Jugut", 'active' => true],
            ['name' =>"Albania", 'name_de' => "Albanien", 'name_al' => "Shqip", 'active' => true],
            ['name' =>"USA", 'name_de' => "USA", 'name_al' => "SHBA", 'active' => true],
            ['name' =>"Arabia", 'name_de' => "Arabien", 'name_al' => "Arabia", 'active' => true],
            ['name' =>"Armenia", 'name_de' => "Armenien", 'name_al' => "Armenia", 'active' => true],
            ['name' =>"Aztec", 'name_de' => "aztekisch", 'name_al' => "aztek", 'active' => true],
            ['name' =>"Basque", 'name_de' => "baskisch", 'name_al' => "bask", 'active' => true],
            ['name' =>"Bulgaria", 'name_de' => "Bulgarien", 'name_al' => "Bullgaria", 'active' => true],
            ['name' =>"China", 'name_de' => "China", 'name_al' => "Kinë", 'active' => true],
            ['name' =>"Dutch", 'name_de' => "Niederländisch", 'name_al' => "holandeze", 'active' => true],
            ['name' =>"Egypt", 'name_de' => "Ägypten", 'name_al' => "Egjipti", 'active' => true],
            ['name' =>"England", 'name_de' => "England", 'name_al' => "Anglia", 'active' => true],
            ['name' =>"Estonia", 'name_de' => "Estland", 'name_al' => "Estonia", 'active' => true],
            ['name' =>"Frence", 'name_de' => "Frankreich", 'name_al' => "Franca", 'active' => true],
            ['name' =>"Germay", 'name_de' => "Deutschland", 'name_al' => "Gjermania", 'active' => true],
            ['name' =>"Greece", 'name_de' => "Griechenland", 'name_al' => "Greqia", 'active' => true],
            ['name' =>"Hawaii", 'name_de' => "Hawaii", 'name_al' => "Havai", 'active' => true],
            ['name' =>"Hebrew", 'name_de' => "hebräisch", 'name_al' => "hebraishtja", 'active' => true],
            ['name' =>"Hungaria", 'name_de' => "Ungarn", 'name_al' => "Hungaria", 'active' => true],
            ['name' =>"Inca", 'name_de' => "Inka", 'name_al' => "Inca", 'active' => true],
            ['name' =>"Indian", 'name_de' => "indisch", 'name_al' => "indiane", 'active' => true],
            ['name' =>"Indonesia", 'name_de' => "Indonesien", 'name_al' => "Indonezia", 'active' => true],
            ['name' =>"Irland", 'name_de' => "Irland", 'name_al' => "Irlanda", 'active' => true],
            ['name' =>"Italy", 'name_de' => "Italien", 'name_al' => "Italia", 'active' => true],
            ['name' =>"Japan", 'name_de' => "Japan", 'name_al' => "Japonia", 'active' => true],
            ['name' =>"Korea", 'name_de' => "Korea", 'name_al' => "Koreja", 'active' => true],
            ['name' =>"Latin", 'name_de' => "Latein", 'name_al' => "latinisht", 'active' => true],
            ['name' =>"Lithuania", 'name_de' => "Litauen", 'name_al' => "Lituania", 'active' => true],
            ['name' =>"Malaysia", 'name_de' => "Malaysia", 'name_al' => "Malajzia", 'active' => true],
            ['name' =>"Maori", 'name_de' => "Maori", 'name_al' => "Maori", 'active' => true],
            ['name' =>"Native American", 'name_de' => "Amerikanischer Ureinwohner", 'name_al' => "Amerikanë vendas", 'active' => true],
            ['name' =>"Persian", 'name_de' => "persisch", 'name_al' => "persisht", 'active' => true],
            ['name' =>"Poland", 'name_de' => "Polen", 'name_al' => "Polonia", 'active' => true],
            ['name' =>"Portugal", 'name_de' => "Portugal", 'name_al' => "Portugalia", 'active' => true],
            ['name' =>"Romanian", 'name_de' => "rumänisch", 'name_al' => "rumun", 'active' => true],
            ['name' =>"Russia", 'name_de' => "Russland", 'name_al' => "Rusia", 'active' => true],
            ['name' =>"Scandinavia", 'name_de' => "Skandinavien", 'name_al' => "Skandinavia", 'active' => true],
            ['name' =>"Norway", 'name_de' => "Norwegen", 'name_al' => "Norvegjia", 'active' => true],
            ['name' =>"Norwegian", 'name_de' => "norwegisch", 'name_al' => "norvegjeze", 'active' => true],
            ['name' =>"Scotland", 'name_de' => "Schottland", 'name_al' => "Skoci", 'active' => true],
            ['name' =>"Slavic", 'name_de' => "Slawisch", 'name_al' => "sllave", 'active' => true],
            ['name' =>"Bosnia", 'name_de' => "Bosnien", 'name_al' => "Bosnjë", 'active' => true],
            ['name' =>"Croatia", 'name_de' => "Kroatien", 'name_al' => "Kroacia", 'active' => true],
            ['name' =>"Spain", 'name_de' => "Spanien", 'name_al' => "Spanja", 'active' => true],
            ['name' =>"Swahili", 'name_de' => "Suaheli", 'name_al' => "Suahili", 'active' => true],
            ['name' =>"Thailand", 'name_de' => "Thailand", 'name_al' => "Tajlandë", 'active' => true],
            ['name' =>"Turkey", 'name_de' => "Truthahn", 'name_al' => "Turqia", 'active' => true],
            ['name' =>"Vietnam", 'name_de' => "Vietnam", 'name_al' => "Vietnami", 'active' => true],
            ['name' =>"Welsh", 'name_de' => "Walisisch", 'name_al' => "Uellsisht", 'active' => true],
            ['name' =>"Eritrea", 'name_de' => "Eritrea", 'name_al' => "Eritrea", 'active' => true],
            ['name' =>"France", 'name_de' => "Frankreich", 'name_al' => "Franca", 'active' => true],
            ['name' =>"Germany", 'name_de' => "Deutschland", 'name_al' => "Gjermania", 'active' => true],
            ['name' =>"India", 'name_de' => "Indien", 'name_al' => "Indi", 'active' => true],
            ['name' =>"Mongolia", 'name_de' => "Mongolei", 'name_al' => "Mongolia", 'active' => true],
            ['name' =>"Iran", 'name_de' => "Iran", 'name_al' => "Irani", 'active' => true],
            ['name' =>"Czech", 'name_de' => "Tschechisch", 'name_al' => "çeke", 'active' => true],
            ['name' =>"celtic", 'name_de' => "keltisch", 'name_al' => "kelt", 'active' => true],
            ['name' =>"Cambodia", 'name_de' => "Kambodscha", 'name_al' => "Kamboxhia", 'active' => true],
            ['name' =>"Romania", 'name_de' => "Rumänien", 'name_al' => "Rumania", 'active' => true],
            ['name' =>"Somali", 'name_de' => "somali", 'name_al' => "somalez", 'active' => true],
            ['name' =>"Hausa", 'name_de' => "Hausa", 'name_al' => "Hausa", 'active' => true],
            ['name' =>"Togo", 'name_de' => "Gehen", 'name_al' => "Togo", 'active' => true],
            ['name' =>"Norwey", 'name_de' => "Norwegen", 'name_al' => "Norvegjia", 'active' => true],
            ['name' =>"Zimbabwe", 'name_de' => "Zimbabwe", 'name_al' => "Zimbabve", 'active' => true],
            ['name' =>"Iceland", 'name_de' => "Island", 'name_al' => "Islanda", 'active' => true],
            ['name' =>"Tahiti", 'name_de' => "Tahiti", 'name_al' => "Tahiti", 'active' => true],
            ['name' =>"Nordic", 'name_de' => "nordisch", 'name_al' => "nordike", 'active' => true],
            ['name' =>"Central Africa", 'name_de' => "Zentralafrika", 'name_al' => "Afrika Qendrore", 'active' => true],
            ['name' =>"Sweden", 'name_de' => "Schweden", 'name_al' => "Suedia", 'active' => true],
            ['name' =>"Finland", 'name_de' => "Finnland", 'name_al' => "Finlanda", 'active' => true],
            ['name' =>"Lesotho", 'name_de' => "Lesotho", 'name_al' => "Lesoto", 'active' => true],
            ['name' =>"Latvia", 'name_de' => "Lettland", 'name_al' => "Letonia", 'active' => true],
            ['name' =>"Zambia", 'name_de' => "Sambia", 'name_al' => "Zambia", 'active' => true],
            ['name' =>"Guinea", 'name_de' => "Guinea", 'name_al' => "Guinea", 'active' => true],
            ['name' =>"Sudan", 'name_de' => "Sudan", 'name_al' => "Sudani", 'active' => true],
            ['name' =>"Mozambik", 'name_de' => "Mosambik", 'name_al' => "Mozambik", 'active' => true],
            ['name' =>"Angola", 'name_de' => "Angola", 'name_al' => "Angola", 'active' => true],
            ['name' =>"Zulu", 'name_de' => "Zulu", 'name_al' => "Zulu", 'active' => true],
            ['name' =>"Gambia", 'name_de' => "Gambia", 'name_al' => "Gambia", 'active' => true],
            ['name' =>"Zaire", 'name_de' => "Zaire", 'name_al' => "Zaire", 'active' => true],
            ['name' =>"Serbia", 'name_de' => "Serbien", 'name_al' => "Serbisë", 'active' => true],
            ['name' =>"Kongo", 'name_de' => "Kongo", 'name_al' => "Kongo", 'active' => true],
            ['name' =>"Mali", 'name_de' => "Mali", 'name_al' => "Mali", 'active' => true],
            ['name' =>"Sauth Africa", 'name_de' => "Sauth Afrika", 'name_al' => "Afrika e Jugut", 'active' => true],
            ['name' =>"Congo", 'name_de' => "Kongo", 'name_al' => "Kongo", 'active' => true],
            ['name' =>"Rwanda", 'name_de' => "Ruanda", 'name_al' => "Ruanda", 'active' => true],
            ['name' =>"Xhosa", 'name_de' => "Xhosa", 'name_al' => "Xhosa", 'active' => true],
            ['name' =>"Sierra Leone", 'name_de' => "Sierra Leone", 'name_al' => "Sierra Leone", 'active' => true],
            ['name' =>"Simbabwe", 'name_de' => "Simbabwe", 'name_al' => "Simbabve", 'active' => true],
            ['name' =>"Algeria", 'name_de' => "Algerien", 'name_al' => "Algjeria", 'active' => true],
            ['name' =>"Namibia", 'name_de' => "Namibia", 'name_al' => "Namibia", 'active' => true],
            ['name' =>"Haiti", 'name_de' => "Haiti", 'name_al' => "Haiti", 'active' => true],
            ['name' =>"Morocco", 'name_de' => "Marokko", 'name_al' => "Maroku", 'active' => true],
            ['name' =>"Islamic Albanian", 'name_de' => "Islamisch Albanisch", 'name_al' => "Shqip Musliman", 'active' => true],
            ['name' =>"Christian Albanian", 'name_de' => "Christlich Albanisch", 'name_al' => "Shqip Krishter", 'active' => true],

        );
        
        Origin::insert($data);
    }
}
